version: "2"
networks:
    demo:
services:  
 
 patroni:
  image: patroni-image 
  networks:
    - postgres-backend
  ports:
    - "8008:8008"
    - "6432:5432"
  user: postgres
  volumes:
    - postgres-data:/var/lib/postgresql/data
  environment:
    PATRONI_POSTGRESQL_DATA_DIR: /var/lib/postgresql/data/node1
  restart: unless-stopped

 pgbouncer:
  image: edoburu/pgbouncer   
#  networks:
#    - postgres-backend
  ports:
    - "5432:5432"
  depends_on:
    - patroni
  environment:
    TZ: Asia/Jakarta
    ADMIN_USERS: admin
    DB_HOST: patroni
    DB_USER: admin
    DB_PASSWORD: admin
    POOL_MODE: transaction
    MAX_CLIENT_CONN: 1000
    DEFAULT_POOL_SIZE: 300
  restart: unless-stopped